Upgrade Grovy to 3.04 to support latest Java versions
jacoco/jacoco pull request #1060
Opened 2020-06-17 20:05 UTC by marchof

Since GMavenPlus 1.9.0 Java 14 and Java 15 is supported. This version of
GMavenPlus requires Groovy 3.x, so also update Groovy to latest version.

For other JVM languages I propose that we focus on the last stable
release, so Groovy 3.x should be ok as a test target.

As Java 7 is not supported any more therefore Groovy tests are now
executed for >= Java 8

This is a rebased/updated version of #1022

2020-08-31 12:41 UTC, henrik242 approved these changes

2020-08-31 12:41 UTC, henrik242 commented on org.jacoco.core.test.validation.groovy/pom.xml
> +    <groovy.version>3.0.4</groovy.version>
This can be bumped to 3.0.5

2020-08-31 12:41 UTC, henrik242 commented on org.jacoco.core.test.validation.groovy/pom.xml
> +    <gmaven.version>1.9.0</gmaven.version>
GmavenPlus can be bumped to  1.10.0

2020-10-16 14:14 UTC, Godin requested changes
> This version of GMavenPlus requires Groovy 3.x

@marchof To me seems that `gmavenplus-plugin` version `1.9.0` and later actually work for latest Groovy 2.x version `2.5.13`, while compilation into bytecode version `14` and above require Groovy 3.x

```
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.9.0:compile (compile) on project org.jacoco.core.test.validation.groovy:
Execution compile of goal org.codehaus.gmavenplus:gmavenplus-plugin:1.9.0:compile failed:
Target bytecode 14 requires Groovy 3.0.0-beta-2 or newer.
```

However I like your proposal

> For other JVM languages I propose that we focus on the last stable release, so Groovy 3.x should be ok as a test target.

So I'll clean it up and then do merge.

2020-10-16 14:14 UTC, Godin commented on org.jacoco.core.test.validation/pom.xml
> -        <module>../org.jacoco.core.test.validation.groovy</module>
I was wondering about the statement

> As Java 7 is not supported any more therefore Groovy tests are now executed for >= Java 8

"not supported" by whom? Apparently it is about Groovy 3 - https://groovy-lang.org/releasenotes/groovy-3.0.html

> Groovy 3.0 requires JDK9+ to build and JDK8 is the minimum version of the JRE

then in `org.jacoco.doc/docroot/doc/build.html` in row `org.jacoco.core.test.validation.groovy` we should replace `7` by `8` and empty cell about `JDK 7`.

2020-10-16 15:01 UTC, Godin approved these changes

2020-10-16 15:52 UTC, merged

2020-10-19 06:03 UTC, marchof commented
@Godin Thanks for updating & cleaning-up!