Move validation tests from Java 20 preview to Java 21
jacoco/jacoco pull request #1478
Opened 2023-06-08 19:59 UTC by marchof

Record patterns and pattern matching for switch have been released in Java 21.

2023-06-08 20:17 UTC, Godin requested changes
```diff
 /**
  * This target exercises pattern matching for switch
- * (<a href="https://openjdk.org/jeps/433">JEP 433</a>).
+ * (<a href="https://openjdk.org/jeps/441">JEP 441</a>).
  */
 public class SwitchPatternMatchingTarget {
```

2023-06-08 20:25 UTC, marchof commented
I was probably too fast here: Latest eclipse-formatter cannot yet cope with this.

@Godin Re-add preview setting only for spotless plugin?

2023-06-08 20:46 UTC, Godin commented
@marchof yes - let's re-add/keep `.settings/org.eclipse.jdt.core.prefs` and relevant part of `pom.xml` for the time being.

2023-06-14 10:04 UTC, Godin approved these changes

2023-06-14 10:04 UTC, merged