Add experimental support for Java 25
jacoco/jacoco pull request #1807
Opened 2024-12-08 08:41 UTC by marchof

Preparing for Java 25. OpenJDK main repo should start with Java 25 next week.

2024-12-08 19:15 UTC, marchof commented
@Godin I tested the change with my arm32 JDK builds: https://pici.beachhub.io/#/jdk-jacoco/20241208-164018

May I ask you to add Java 25 to our CI?

2024-12-09 09:29 UTC, Godin requested changes

2024-12-09 09:29 UTC, Godin commented on org.jacoco.doc/docroot/doc/faq.html
> +  experimental support for class files of version 24 and 25 is provided.
```suggestion
  experimental support for class files of versions 24 and 25 is provided.
```

2024-12-09 11:19 UTC, ice1000 commented
Nice!!

2024-12-09 11:32 UTC, Godin approved these changes

2024-12-09 11:32 UTC, merged